// Generated by CoffeeScript 1.6.3
(function() {
  var PauseStatus, RunningStatus, StopStatus, StopWatch, StopWatchView;

  StopStatus = (function() {
    function StopStatus(app, view) {
      this.app = app;
      this.view = view;
    }

    StopStatus.prototype.onBeforeChangeStatus = function() {
      this.view.updateDisplay();
      this.view.decorateRunButton('main');
      return this.view.decorateDisabledLapButton('sub');
    };

    StopStatus.prototype.clickedMainButton = function() {
      return this.app.run();
    };

    StopStatus.prototype.clickedSubButton = function() {};

    return StopStatus;

  })();

  PauseStatus = (function() {
    function PauseStatus(app, view) {
      this.app = app;
      this.view = view;
    }

    PauseStatus.prototype.onBeforeChangeStatus = function() {
      this.view.decorateRunButton('main');
      return this.view.decorateResetButton('sub');
    };

    PauseStatus.prototype.clickedMainButton = function() {
      return this.app.run();
    };

    PauseStatus.prototype.clickedSubButton = function() {
      return this.app.reset();
    };

    return PauseStatus;

  })();

  RunningStatus = (function() {
    function RunningStatus(app, view) {
      this.app = app;
      this.view = view;
    }

    RunningStatus.prototype.onBeforeChangeStatus = function() {
      this.view.decorateStopButton('main');
      return this.view.decorateLapButton('sub');
    };

    RunningStatus.prototype.clickedMainButton = function() {
      return this.app.pause();
    };

    RunningStatus.prototype.clickedSubButton = function() {
      return this.app.lap();
    };

    return RunningStatus;

  })();

  StopWatch = (function() {
    function StopWatch() {}

    StopWatch.prototype.setup = function(el) {
      this.view = new StopWatchView(this, $(el));
      this.statuses = {
        stop: new StopStatus(this, this.view),
        pause: new PauseStatus(this, this.view),
        running: new RunningStatus(this, this.view)
      };
      return this.reset();
    };

    StopWatch.prototype.clickedMainButton = function() {
      return this.status.clickedMainButton();
    };

    StopWatch.prototype.clickedSubButton = function() {
      return this.status.clickedSubButton();
    };

    StopWatch.prototype.run = function() {
      var _this = this;
      this.changeStatus(this.statuses.running);
      return this.timer = setInterval(function() {
        _this.counter++;
        return _this.view.updateDisplay();
      }, 100);
    };

    StopWatch.prototype.pause = function() {
      clearInterval(this.timer);
      return this.changeStatus(this.statuses.pause);
    };

    StopWatch.prototype.reset = function() {
      this.counter = 0;
      this.lastLap = 0;
      this.view.reset();
      return this.changeStatus(this.statuses.stop);
    };

    StopWatch.prototype.lap = function() {
      var lap;
      lap = this.counter - this.lastLap;
      this.lastLap = this.counter;
      return this.view.addLap(lap);
    };

    StopWatch.prototype.changeStatus = function(next) {
      this.status = next;
      return this.status.onBeforeChangeStatus();
    };

    return StopWatch;

  })();

  StopWatchView = (function() {
    function StopWatchView(app, el) {
      var _this = this;
      this.app = app;
      this.$el = $(el);
      this.$('.buttons button.main').click(function(event) {
        return _this.app.clickedMainButton();
      });
      this.$('.buttons button.sub').click(function(event) {
        return _this.app.clickedSubButton();
      });
    }

    StopWatchView.prototype.$ = function(options) {
      return this.$el.find(options);
    };

    StopWatchView.prototype.getButton = function(name) {
      return this.$(".buttons button." + name);
    };

    StopWatchView.prototype.decorateRunButton = function(name) {
      return this.getButton(name).text('run').removeAttr('disabled');
    };

    StopWatchView.prototype.decorateStopButton = function(name) {
      return this.getButton(name).text('stop').removeAttr('disabled');
    };

    StopWatchView.prototype.decorateResetButton = function(name) {
      return this.getButton(name).text('reset').removeAttr('disabled');
    };

    StopWatchView.prototype.decorateLapButton = function(name) {
      return this.getButton(name).text('lap').removeAttr('disabled');
    };

    StopWatchView.prototype.decorateDisabledLapButton = function(name) {
      return this.getButton(name).text('lap').attr('disabled', true);
    };

    StopWatchView.prototype.updateDisplay = function() {
      return this.$('.display').text(this.app.counter);
    };

    StopWatchView.prototype.addLap = function(lap) {
      return $("<li>" + lap + "</li>").prependTo(this.$('.laps'));
    };

    StopWatchView.prototype.clearLaps = function() {
      return this.$('.laps').empty();
    };

    StopWatchView.prototype.reset = function() {
      this.updateDisplay();
      return this.clearLaps();
    };

    return StopWatchView;

  })();

  $(function() {
    var stopWatch;
    stopWatch = new StopWatch();
    return stopWatch.setup($('.stopwatch'));
  });

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
